name: Challenge-SRE-CICD
on:
  pull_request:
    branches: [ main ]

jobs:
  run-cicd:
    runs-on: ubuntu-20.04
    name: run-cicd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Dependencies
        run: mvn clean install
  
      - name: Build and push the tagged docker image to Artifactory Registry
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t us-central1-docker.pkg.dev/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          run: |-
            gcloud container images add-tag \
            us-central1-docker.pkg.dev/plataforma-3/plataforma-3-repository/javaapi:latest \
            ${{ inputs.gcr-repository }}/
            