name: Challenge-SRE-CICD
on:
  push:
    branches: 
      - main

jobs:
  run-cicd:
    runs-on: ubuntu-20.04
    name: run-cicd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Dependencies
        run: mvn clean install 
  